### ISSUE TITLE
Broken link on web export

### ISSUE THREAD

**Issue by lcpdn** [adulau/threat-intelligence.eu#8]
Hello there !
Thanks for the work :)

- **Problem** : The link of the epub version of Psychology of Intelligence Analysis is broken on the website version of the "books" page : https://threat-intelligence.eu/books/ but works fine on the Github "version"
- **Current is** : https://threat-intelligence.eu/books/files/Psychology_of_Intelligence_Analysis_Richards_Heuer.epub
- **Should be**: https://threat-intelligence.eu/files/Psychology_of_Intelligence_Analysis_Richards_Heuer.epub
- **Fix could be** : I don't understand enough Jekyll and Github to submit a fix, sorry

**Comment by adulau** [comment]
Thank you! fixed in 75179cba88d30c4866a22cb5dee2080680500531
